project:
  type: manuscript
  execute-dir: project


manuscript:
  article: manuscript.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  pdf: default


execute:
  freeze: auto
